services:
  # default configuration for services in *this* file
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  app.client.gitlab:
    class: GuzzleHttp\Client
    arguments:
      - headers:
          Accept: 'application/json'
          Content-type: 'application/json'
          Private-Token: '%env(resolve:GITLAB_PRIVATE_TOKEN)%'
        base_uri: '%env(resolve:GITLAB_BASE_URL)%'

