api_platform:
    title: DAGOBAH TASK API
    version: 1.0.0
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
    docs_formats:
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: false
        normalization_context:
            skip_null_values: false
        pagination_client_enabled: true
        pagination_client_items_per_page: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header